### ISSUE TITLE
Java error: Null Pointer Exception

### ISSUE THREAD

**Issue by jbird361** [Kingsford-Group/kourami#12]
I have an issue with my one sample, out of 12, in which I get the following java error during read loading:

java.lang.NullPointerException
        at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:156)
        at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:193)
        at HLAGraph.addAndIncrement(HLAGraph.java:274)
        at HLAGraph.incrementWeight(HLAGraph.java:297)
        at HLAGraph.addWeight(HLAGraph.java:460)
        at HLA.processRecord(HLA.java:233)
        at HLA.loadReads(HLA.java:188)
        at HLA.main(HLA.java:567)
>>>>>>>>>>> source NULL <<<<<<<<<<<

The other 11 samples work, and all the files were generated using the same methodology:
Bam files unmapped using Picard > Unmapped bam files converted to fastq using Picard > fastq aligned using BWA-mem.

**Comment by heewookl** [comment]
Hi,

Would it be possible for you to share the bam file you are having trouble with? 

Thank you.

**Comment by jbird361** [comment]
I've made the file available on onedrive:
https://1drv.ms/u/s!AjV03GXSpf5GmbBM3a3Qn_RWebohWA

**Comment by heewookl** [comment]
Thanks for uploading the bam file. The error is caused by alignments starting with insertions or insertions immediately following soft clipped sequences in CIGAR string. I have updated the code in issue12 branch : https://github.com/Kingsford-Group/kourami/tree/issue12

Your input file will run fine but I dont' recommend using your input file as they were not produced by using preprocessing scripts that are included in Kourami.  The data you are using is NA19239 data from 1000 Genomes with 250bp x 2. Did you want to include unmapped reads to test something out?  Based on our internal testing, including unmapped reads does not really help. 

Instead of your own pipeline (Bam files unmapped using Picard > Unmapped bam files converted to fastq using Picard > fastq aligned using BWA-mem), I recommend using the scripts that are provided as a part of Kourami to extract reads and align them to Kourami-formatted database sequences. You can read this document: https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md
